name: Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Set up QEMU for multiarch building
        uses: docker/setup-qemu-action@v3
      -
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            bergie/shell:latest
